'''
# gmm_classifier.py  — imported by the C++ embedder
# This module defines a single function, gen_clustered(), which is identical to gen_clustered_data() in glow_up.py 
# used in the Python-based analysis pipeline, except that this one operates on the species-specific vectors
# generated by the C++ code, and is designed to be called from the C++ code in real-time as frames are generated.
# gen_clustered_online(Rho_t, const_index, L, aval, Tval, Rval,
#                      n_clusters=2, periodic=True,
#                      evaluate_clusterfrequencies=True)
#
# Rho_t        : np.ndarray, shape (Sp, L*L), dtype float64, unnormalised
# const_index  : np.ndarray or list of int, indices into axis-0 of Rho_t
#                that should be classified. Others are filled with np.nan.
# L            : int, grid side length (L*L must equal Rho_t.shape[1])
# aval, Tval, Rval : strings, used for logging/error messages only
# n_clusters   : int, number of GMM components (almost always 2)
# periodic     : bool, periodic boundary conditions for ndimage.label
# evaluate_clusterfrequencies : bool
#   if True  — also returns a float64 array of shape (Sp, 3, max_sizes)
#              where axis-1 rows are [sizes, counts, freqs], np.nan-padded
#   if False — returns None for that output
# gen_GMMframe : bool, 
#   if True  — also returns a float64 array of shape (Sp, L*L) with the GMM-classified binary mask 
#   for each species (NaN at unselected rows)
#   if False — returns None for that output
#
# Returns:
#   scalar_stats : dict of str -> np.ndarray shape (Sp,), float64
#       keys: "clus_density", "occupied_site_frac",
#             "mean_sq_dist_lcenter", "mean_sq_dist_ucom",
#             "mean_cluster_size", "var_cluster_size", "num_clusters"
#   freq_array   : np.ndarray shape (Sp, 3, max_sizes) or None
#   gmm_frames   : np.ndarray shape (Sp, L*L) or None 
'''
import numpy as np
#import pandas as pan
from sklearn.mixture import GaussianMixture
from scipy import ndimage
from collections import Counter, defaultdict

# Replacing Lambda functions for defaultdict initialisation to avoid pickling issues with multiprocessing
def default_dict():
    return defaultdict(dict)

def nested_default_dict():
    return defaultdict(default_dict)

def double_nested_default_dict():
    return defaultdict(nested_default_dict)

def recursively_nested_default_dict(iter):
    if iter == 0:
        return defaultdict(dict)
    else:
        return defaultdict(recursively_nested_default_dict(iter-1))

# Scalar stat keys — defines output order seen by C++ side
STAT_KEYS = [
    "clus_density",
    "occupied_site_frac",
    "mean_sq_dist_lcenter",
    "mean_sq_dist_ucom",
    "mean_cluster_size",
    "var_cluster_size",
    "num_clusters",
]


def gen_clustered(Rho_t, const_index, L, aval, Tval, Rval, n_clusters=2, periodic=True, evaluate_clusterfrequencies=True, gen_GMMframe=False):

    Rho_t = np.asarray(Rho_t, dtype=np.float64)
    const_index = np.asarray(const_index, dtype=np.intp)
    Sp = Rho_t.shape[0]

    assert Rho_t.ndim == 2, f"[T={Tval} a={aval} R={Rval}] Rho_t must be 2D, got shape {Rho_t.shape}"
    assert Rho_t.shape[1] == L * L, f"[T={Tval} a={aval} R={Rval}] Rho_t.shape[1]={Rho_t.shape[1]} != L*L={L*L}"

    # Initialise all scalar output arrays to nan (Sp,) — only selected species in const_index will be filled with real values, others remain nan.
    # scalar_stats is a dict of str -> np.ndarray shape (Sp,), float64, with keys defined by STAT_KEYS.
    scalar_stats = {k: np.full(Sp, np.nan, dtype=np.float64) for k in STAT_KEYS}

    # Per-species storage for cluster-size arrays (ragged before padding)
    # Only allocated if evaluate_clusterfrequencies=True
    raw_sizes_list  = [None] * Sp  # will hold 1-D int arrays of cluster sizes
    # Allocate gmm_frames as NaN array if requested; only selected species will be filled.
    gmm_frames = np.full((Sp, L * L), np.nan, dtype=np.float64) if gen_GMMframe else None
    center = np.array([L / 2.0, L / 2.0])

    for i in const_index:
        i = int(i)
        if i < 0 or i >= Sp:
            print(f"For [t, a, j] [{Tval} , {aval} , {Rval}], const_index entry {i} out of range [0, {Sp}). Skipping....")
            continue

        raw = Rho_t[i]   # shape (L*L,)

        # --- normalise by column max (mirrors gen_clustered_data) ---
        col_max = raw.max()
        if col_max == 0.0:
            print(f"WARNING: At [t, a, j, s] [{Tval} , {aval} , {Rval} , {i}] \t: entirely zero column. Filling with nan.")
            continue   # scalar_stats already nan at index i

        if raw.std() < 1e-6:
            print(f"WARNING: At [t, a, j, s] [{Tval} , {aval} , {Rval} , {i}] \t: flat column (std < 1e-6). Filling with nan.")
            continue

        normed = raw / col_max   # shape (L*L,)

        # --- GMM classification ---
        try:
            gmm = GaussianMixture(n_components=n_clusters, covariance_type='full', 
                    random_state=np.random.randint(1,1000)).fit(normed.reshape(-1, 1))
            labels  = gmm.fit_predict(normed.reshape(-1, 1))
            centers = gmm.means_.flatten()
        except Exception as e:
            print(f"[T={Tval} a={aval} R={Rval}] "
                  f"Species {i}: GMM failed ({e}). Filling with nan.")
            continue

        # Reorder labels so 0 = lowest center (mirrors gen_clustered_data)
        order     = np.argsort(centers)
        label_map = {old: new for new, old in enumerate(order)}
        labels    = np.vectorize(label_map.get)(labels)
        #labels = np.take(np.array([label_map[k] for k in sorted(label_map)]), labels)

        binary_mask = (labels > 0).astype(np.int32).reshape(L, L)

        # --- Store classified frame as float (NaN at unselected rows) ---
        if gen_GMMframe:
            gmm_frames[i] = binary_mask.flatten().astype(np.float64)

        # --- frame macrostats (mirrors macro_framestats_dict block) ---
        active_flat = binary_mask.flatten() > 0
        n_active    = active_flat.sum()

        scalar_stats["clus_density"][i] = normed[active_flat].mean() if n_active > 0 else 0.0
        scalar_stats["occupied_site_frac"][i] = n_active / (L * L)

        indices = np.argwhere(binary_mask > 0)   # shape (n_active, 2)
        if n_active > 0:
            scalar_stats["mean_sq_dist_lcenter"][i] = np.mean(np.sum((indices - center) ** 2, axis=1))
            ucom = indices.mean(axis=0)
            scalar_stats["mean_sq_dist_ucom"][i] = np.mean(np.sum((indices - ucom) ** 2, axis=1))
        else:
            scalar_stats["mean_sq_dist_lcenter"][i] = 0.0
            scalar_stats["mean_sq_dist_ucom"][i]    = 0.0

        # Count the size of each cluster in col using scipy.ndimage.label.
        non_periodic_labels, _ = ndimage.label(binary_mask, structure=np.ones((3, 3)))

        if periodic:
            for x in range(L):
                if non_periodic_labels[x, 0] > 0 and non_periodic_labels[x, -1] > 0:
                    non_periodic_labels[non_periodic_labels == non_periodic_labels[x, -1]] = non_periodic_labels[x, 0]
            for x in range(L):
                if non_periodic_labels[0, x] > 0 and non_periodic_labels[-1, x] > 0:
                    non_periodic_labels[non_periodic_labels == non_periodic_labels[-1, x]] = non_periodic_labels[0, x]
            label_ids = np.unique(non_periodic_labels)
            for idx in range(1, len(label_ids)):
                if label_ids[idx] != label_ids[idx - 1] + 1:
                    non_periodic_labels[non_periodic_labels == label_ids[idx]] = label_ids[idx - 1] + 1
                    label_ids[idx] = label_ids[idx - 1] + 1

        Clus_ID, Clus_Sizes = np.unique(non_periodic_labels, return_counts=True)
        Clus_Sizes = Clus_Sizes[1:]   # drop background label 0

        # --- cluster macrostats (mirrors macro_clusterstats_dict block) ---
        if len(Clus_Sizes) > 0:
            scalar_stats["mean_cluster_size"][i] = float(Clus_Sizes.mean())
            scalar_stats["var_cluster_size"][i]  = float(Clus_Sizes.var())
            scalar_stats["num_clusters"][i]      = float(len(Clus_Sizes))
        else:
            scalar_stats["mean_cluster_size"][i] = 0.0
            scalar_stats["var_cluster_size"][i]  = 0.0
            scalar_stats["num_clusters"][i]      = 0.0

        # Store raw sizes for frequency array construction below
        if evaluate_clusterfrequencies:
            raw_sizes_list[i] = Clus_Sizes   # 1-D int array

    # --- build cluster frequency array (Sp, 3, max_sizes) ---
    freq_array = None
    if evaluate_clusterfrequencies:
        # Find global max number of distinct sizes across all selected species.
        # Unselected or failed species have raw_sizes_list[i] = None.
        n_sizes_per_species = [
            len(np.unique(raw_sizes_list[i])) if raw_sizes_list[i] is not None else 0
            for i in range(Sp)
        ]
        max_sizes = max(n_sizes_per_species) if any(n > 0 for n in n_sizes_per_species) else 0

        if max_sizes > 0:
            freq_array = np.full((Sp, 3, max_sizes), np.nan, dtype=np.float64)

            for i in const_index:
                if raw_sizes_list[i] is None or len(raw_sizes_list[i]) == 0:
                    continue

                sizes = raw_sizes_list[i]           # raw per-site sizes
                unique_sizes, counts = np.unique(sizes, return_counts=True)
                total = counts.sum()
                freqs = counts / total if total > 0 else np.zeros_like(counts, dtype=np.float64)

                n = len(unique_sizes)
                freq_array[i, 0, :n] = unique_sizes.astype(np.float64)
                freq_array[i, 1, :n] = counts.astype(np.float64)
                freq_array[i, 2, :n] = freqs
                # Remaining [:, n:] columns stay np.nan (already initialised)

    return scalar_stats, freq_array, gmm_frames